# Week 1 Lab Assignments

You are required to implement the following functions:
- `homogenous_transform_2D` - Perform homogenous transformations for a 2D system
- `homogenous_transform_3D` - Perform homogenous transformations for a 3D system
- `chain_transforms` - Perform a chain of 3D transformations in the given order


In [1]:
# import required libraries
import numpy as np
import matplotlib.pyplot as plt
# To render plots inline
%matplotlib inline

# For unit tests
from tester import LabTester
lab_tester = LabTester()

In [30]:
# Homogenous 2D Transformation
def homogenous_transform_2D(V:np.ndarray, U:np.ndarray, theta:float) -> np.ndarray:
    """
    Input:
        V       - initial vector
        U       - translation vector
        theta   - angle in degrees
    Output: resulting coordinates after rotating V by theta and translating by U
    """
    
    # Your code here
    alpha = np.radians(theta)
    R = np.array([
        [np.cos(alpha), -np.sin(alpha), U[0]],
        [np.sin(alpha),  np.cos(alpha), U[1]],
        [0, 0, 1]
    ])
    t = np.array([V[0],V[1],1])
    result = np.dot(R,t)
    output = np.array([result[0],result[1]])
#     print("Inside",trans)
#     print("Rot_vec",Rot_Vec)
#     print("result",result)
    return output
    
    pass

## Lab 1: Homogeneous Transformation in 2D
- *Theory*: Translating and rotating a point using homogeneous transformations.
- *Task*: Implement a function that applies a 2D homogeneous transformation matrix to a given point.
- *Expected Output*: Given a vector $(1,0)$ applying a translation of $(3,4)$ and a $\theta = 45°$ rotation, the transformed point should be $(3.707, 4.707)$

In [31]:
lab_tester.test_homogeneous_transform_2d(homogenous_transform_2D)


=== Testing 2D Homogeneous Transformation Implementation ===
✅ Combined transform: translation(3,4) + rotation(45°)
✅ Pure translation: no rotation


In [171]:
import numpy as np

def homogenous_transform_3D(V: np.ndarray, U: np.ndarray, theta: dict) -> np.ndarray:
    """
    Input:
        V       - initial vector
        U       - translation vector
        theta   - dictionary of angles with the 'x', 'y', and 'z' angles
    Output: resulting coordinates after rotating V by theta and translating by U
    """

    # Default rotation angles in radians (0 radians for all axes if not provided)
    theta_x = theta.get("x", 0)
    theta_y = theta.get("y", 0)
    theta_z = theta.get("z", 0)

    # Convert to radians
    theta_x = np.radians(theta_x)
    theta_y = np.radians(theta_y)
    theta_z = np.radians(theta_z)

    # Rotation matrices for each axis (in order Z, Y, X)
    R_z = np.array([
        [np.cos(theta_z), -np.sin(theta_z), 0],
        [np.sin(theta_z), np.cos(theta_z), 0],
        [0, 0, 1]
    ])
    
    R_y = np.array([
        [np.cos(theta_y), 0, np.sin(theta_y)],
        [0, 1, 0],
        [-np.sin(theta_y), 0, np.cos(theta_y)]
    ])
    
    R_x = np.array([
        [1, 0, 0],
        [0, np.cos(theta_x), -np.sin(theta_x)],
        [0, np.sin(theta_x), np.cos(theta_x)]
    ])

    # Combine the rotation matrices (Z -> Y -> X)
    R = np.dot(R_z, np.dot(R_y, R_x))

    # Transformation matrix with rotation and translation
    T_R = np.array([
        [R[0, 0], R[0, 1], R[0, 2], U[0]],
        [R[1, 0], R[1, 1], R[1, 2], U[1]],
        [R[2, 0], R[2, 1], R[2, 2], U[2]],
        [0, 0, 0, 1]
    ])

    # Homogeneous coordinate for input vector V
    V_homogeneous = np.array([V[0], V[1], V[2], 1])

    # Apply transformation (rotation + translation)
    result = np.dot(T_R, V_homogeneous)
    
    print(V)
    print(U)
    print(theta)
    # Output in 3D (rounded if necessary)
    output = np.array([round(result[0]), round(result[1]), round(result[2])])
    return output


## Lab 4: Homogeneous Transformation in 3D
- *Theory*: Extending 2D transformations to 3D space.
- *Task*: Implement a function that applies a 3D transformation matrix to a point in 3D.
- *Expected Output*: Given a vector $(2,3,4)$ appying a translation of $(5,5,5)$ and a rotation of $\theta = 90°$ about the z-axis the transformed point should be $(2,7,9)$.

In [172]:
lab_tester.test_homogeneous_transform_3d(homogenous_transform_3D)


=== Testing 3D Homogeneous Transformation Implementation ===
[2 3 4]
[5 5 5]
{'z': 90}
❌ Combined 3D transform: translation(5,5,5) + rotation(90° about z)
   Expected: [-8, 7, 9]
   Got: [2 7 9]
[1 2 3]
[4 5 6]
{'x': 0, 'y': 0, 'z': 0}
✅ Pure 3D translation: no rotation
[1 1 0]
[0 0 0]
{'x': 90}
✅ Pure rotation about x-axis
[1 0 0]
[0 0 0]
{'x': 90, 'y': 90, 'z': 90}
❌ Combined rotations about x, y, and z axes
   Expected: [0, 0, 1]
   Got: [ 0  0 -1]
[1 2 3]
[-1 -1 -1]
{'x': 90, 'y': 90, 'z': 90}
❌ Rotations with Negative Translation
   Expected: [2, -1, 0]
   Got: [ 2  1 -2]
[1 2 3]
[-5  5 -1]
{'x': 60, 'y': 90, 'z': 30}
❌ Rotations by odd angles with Translation
   Expected: [2, -4, 7]
   Got: [-1  5 -2]


## Lab 5: Chain Transformations
- *Theory*: Combining multiple transformations using matrix multiplication.
- *Task*: Implement a function that applies multiple homogeneous transformations sequentially.
- *Expected Output*: Given a sequence of rotations and translations, compute the final transformed position.

In [182]:
# Chain transformations
def chain_transforms(V:np.ndarray, transforms:list) -> np.ndarray:
    """
    Input:
        V           - initial vector
        transforms  - list of 'translation' and 'rotation' - ex:{'translation': np.array([0, 0, 0]), 'rotation': {'z': 0}}
    Output: resulting coordinates after appyling the transforms in the given order
    """
#     print(V)
#     print(transforms)
    
    # Your code here
    for dict in transforms:
        U = dict.get("translation",np.array([0,0,0]))
        theta = dict.get("rotation",{"x":0,"y":0,"z":0})

        V = homogenous_transform_3D(V, U,theta) 
    pass

In [183]:
lab_tester.test_chain_transformations(chain_transforms)


=== Testing Chain Transformations Implementation ===
[1 1 1]
[1 0 0]
{'z': 0}
[2 1 1]
[0 1 0]
{'z': 0}


TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

In [ ]:
# Summary of test results
lab_tester.print_summary()